(Fri Sep  6 12:55:25 2024)(-0.41256 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/lib/libscanner_great.so".

Raised at: line 361 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0251322 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_dynesty" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_dynesty.py(14): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0261395 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_emcee" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_emcee.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0269324 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_nautilus" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_nautilus.py(6): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0278829 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_nessai" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_nessai.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0288592 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_pocomc" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_pocomc.py(10): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0296947 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_scipy" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_scipy.py(6): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0304595 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_ultranest" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_ultranest.py(9): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.03121 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_zeus" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_zeus.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0316148 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"grid" was not loaded: ModuleNotFoundError: No module named 'scanner_plugin'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/grid.py(12): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0383688 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_dynesty" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_dynesty.py(14): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.039129 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_emcee" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_emcee.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0399011 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_nautilus" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_nautilus.py(6): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0406303 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_nessai" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_nessai.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0413782 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_pocomc" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_pocomc.py(10): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0421448 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_scipy" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_scipy.py(6): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0635532 [s])(Rank 1)[Default,Utilities]:
Random number engine mt19937_64 (default) selected with seed 559936235.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0428816 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_ultranest" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_ultranest.py(9): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0435883 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_zeus" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_zeus.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.044055 [s])(Rank 1)[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"grid" was not loaded: ModuleNotFoundError: No module named 'scanner_plugin'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/grid.py(12): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0653622 [s])(Rank 1)[Default,Core]:
Starting scan.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0861257 [s])(Rank 1)[Default,Printers][Info]:
Assigned printer ID '0' to output quantity with label 'LogLike'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.08617 [s])(Rank 1)[Default,Printers][Info]:
Assigned printer ID '1' to output quantity with label 'pointID'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.086193 [s])(Rank 1)[Default,Printers][Info]:
Assigned printer ID '2' to output quantity with label 'MPIrank'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0864526 [s])(Rank 1)[Default,Printers][Info]:
Assigned printer ID '3' to output quantity with label 'Posterior'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0864919 [s])(Rank 1)[Default,Printers][Info]:
Assigned printer ID '4' to output quantity with label 'LastLive'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0873328 [s])(Rank 1)[Default,Printers][Info]:
Assigned printer ID '5' to output quantity with label 'default::z'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0874171 [s])(Rank 1)[Default,Printers][Info]:
Assigned printer ID '6' to output quantity with label 'default::y'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0874591 [s])(Rank 1)[Default,Printers][Info]:
Assigned printer ID '7' to output quantity with label 'default::x'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:25 2024)(0.0876517 [s])(Rank 1)[Default,Printers][Info]:
Assigned printer ID '8' to output quantity with label 'ModifiedLogLike'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:27 2024)(1.64483 [s])(Rank 1)[Default,Printers][Info]:
Gathering sync buffer data from all processes to rank 0 process...
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:27 2024)(1.64492 [s])(Rank 1)[Default,Printers][Info]:
Gathering data on number of points and buffers to be transmitted
Number of points to send from this process: 499
Number of buffers to send from this process: 7

--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:27 2024)(1.64495 [s])(Rank 1)[Default,Printers][Info]:
Gathered data:
Number of points to recv from each process: [499, 499 ]
Number of buffers to recv from each process: [7, 7 ]

--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:27 2024)(1.64599 [s])(Rank 1)[Default,Printers][Info]:
Gathering buffer data for processes [0, 1 ]
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:27 2024)(1.65545 [s])(Rank 1)[Default,Printers][Info]:
Gathering buffer block size data (number of buffer blocks to transmit from this process: 50)
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:27 2024)(1.65556 [s])(Rank 1)[Default,Printers][Info]:
Performing Gatherv of buffer data blocks...
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:27 2024)(1.65624 [s])(Rank 1)[Default,Printers][Info]:
Gathering random-access print buffer data from all process to rank 0 process...
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:27 2024)(1.65627 [s])(Rank 1)[Default,Printers][Info]:
Gathering data on number of points and buffers to be transmitted
Number of points to send from this process: 0
Number of buffers to send from this process: 0

--<>--<>--<>--<>--<>--<>--<>--
